Update before posting
kspieks/chemprop pull request #1
Opened 2024-10-08 06:43 UTC by xiaoruiDong

This PR includes necessary changes to allow training with frozen weights and helper scripts for inference.

2024-10-09 16:13 UTC, kspieks requested changes
Thanks Xiaorui! This PR looks great. Thanks for creating organized scripts with excellent documentation and comments. I had a few minor questions/comments but we can definitely merge soon

2024-10-09 16:13 UTC, kspieks commented on paper_results/scripts/predict_DMPNN1.sh
> +# However, if runing into issues, you may manually set this path
Can you please change "runing" to "running"?

2024-10-09 16:13 UTC, kspieks commented on paper_results/scripts/predict_DMPNN1.sh
> +rxn_column="rxn_smiles"s
Is the `s` supposed to be here?

2024-10-09 16:13 UTC, kspieks commented on paper_results/scripts/predict_DMPNN1.sh
> +echo "# Predict Gibbs free energy of activation and of reaction using D-MPNN-1 #"
Can we be more specific with this print statement about which ΔG is being predicted? e.g., specify that it's the Gibbs free energy of activation and of reaction in solution (water)?

2024-10-09 16:13 UTC, kspieks commented on paper_results/scripts/README.md
> +- `predict_DMPNN2.sh` can be used to conduct inference using D-MPNN-2 model. You may open the file and modify the arguments according to your need and setup.
Can we add a note here that recommends users only make predictions using one of the 40 solvents from the paper? I assume the model will perform poorly if users provide a different solvent so we should just give them a heads up about that

2024-10-09 16:13 UTC, kspieks commented on paper_results/scripts/merge_data.py
> +    # Computat solvated barrier heights
Should this say "Compute solvated barrier heights"?

2024-10-10 02:44 UTC, xiaoruiDong commented on paper_results/scripts/merge_data.py
> +    # Computat solvated barrier heights
Thanks

2024-10-10 02:45 UTC, xiaoruiDong commented
@kspieks Thank you for reviewing this PR! Good catches!  Typos are fixed, and instructions are updated.

2024-10-10 07:31 UTC, kspieks commented
Thanks Xiaorui. LGTM

2024-10-10 07:31 UTC, merged